"""Remove tables for admins and moderators

Revision ID: 04df12f7e2c5
Revises: 7973da212e6d
Create Date: 2022-01-10 00:53:12.980123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04df12f7e2c5'
down_revision = '7973da212e6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecotrails_visited', sa.Column('ecotrail_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ecotrails_visited', 'ecotrails', ['ecotrail_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ecotrails_visited', type_='foreignkey')
    op.drop_column('ecotrails_visited', 'ecotrail_id')
    # ### end Alembic commands ###
