"""Made some refarctoring and restructuring of the database models - delete moderators and administrators models, also added two new models and functionality for them - visited ecotrails and planned ectorails.

Revision ID: 6e562c7345c1
Revises: 04df12f7e2c5
Create Date: 2022-01-10 22:51:35.701447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e562c7345c1'
down_revision = '04df12f7e2c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecotrails_planned',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=False),
    sa.Column('area', sa.String(length=255), nullable=False),
    sa.Column('mountain', sa.String(length=255), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('denivelation', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('ecotrail_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ecotrail_id'], ['ecotrails.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ecotrails_planned')
    # ### end Alembic commands ###
