"""remove username column from users mode

Revision ID: 71e160c9b349
Revises: a1c6cae77bed
Create Date: 2022-01-09 00:34:18.764894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '71e160c9b349'
down_revision = 'a1c6cae77bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecotrails', sa.Column('length', sa.Float(), nullable=False))
    op.add_column('ecotrails', sa.Column('denivelation', sa.Integer(), nullable=True))
    op.drop_column('ecotrails', 'difference_in_altitude')
    op.drop_column('ecotrails', 'distance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecotrails', sa.Column('distance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('ecotrails', sa.Column('difference_in_altitude', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('ecotrails', 'denivelation')
    op.drop_column('ecotrails', 'length')
    # ### end Alembic commands ###
