"""Adding DB Model for visited ecotrails

Revision ID: 7973da212e6d
Revises: 0483abcd208a
Create Date: 2022-01-09 20:41:39.670133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7973da212e6d'
down_revision = '0483abcd208a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecotrails_visited',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=False),
    sa.Column('area', sa.String(length=255), nullable=False),
    sa.Column('mountain', sa.String(length=255), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('denivelation', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ecotrails_planned')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecotrails_planned',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('photo_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('area', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('mountain', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('length', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('denivelation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('create_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='ecotrails_planned_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ecotrails_planned_pkey')
    )
    op.drop_table('ecotrails_visited')
    # ### end Alembic commands ###
